
//Messages that are returned to client in API responses
module.exports = {
  ErrorMessage: {
      InvalidUserName: "Invalid username",
      InvalidUserNamePassword: "Invalid username/password",
      InvalidCurrentPassword: "Invalid Current Password",
      InvalidPassword: "Invalid password",
      AccountSuspended: "User account suspended by admin",
      EmailIdNotExist: "Email id not exist",
      UserNotFound: "User not found",
      OtpExpired: "Otp was expired please resend",
      SessionExists: "User already have another logged in session",
      EmailAndPhoneNotExist: "Unable to process request when email and phone is empty",
      PasswordAlreadyUsed: "This password has already been used, you cannot use your last three passwords",
      SystemNotIdenfiedRole: "System not idetified the role",
      FilesNotFound: "Files not found",
      SomethingWentWrong: "Something went wrong, please try again after some time",
      InvalidApplicationId: "Not Allowed. Invalid application ID",
      AccessDenied: "Access Denied: You do not have correct privilege to perform this operation",
      SocketAuthenticationError: "Socket Authentication error : App-Id missing/invalid",
      SocketValidationError: "Socket Validation error",
      InvalidUrl: "Invalid URL",
      UrlExpired: "URL Expired",
      InvalidRequestJson: "Invalid request JSON",
      AccountInactive:"User account is inactive",

      InviteAlreadyCancelled: "Invite was already cancelled",
      UserAlreadyRegistered : "User already registered the invite",
      FirstNameLastNameEmpty : "Unable to process request when first name and last name is empty",
      InvalidEmail: "Unable to process request when email id is invalid",
      InvalidPhone: "Unable to process request when phone number is invalid"
  },
  SuccessMessage: {
      Success: "Success",  
      OtpSentSuccessfully: "Otp has been sent to the email address in our system",
      UserRegisterSuccessfully: "User registered successfully",
      LogoutSuccessFully: "Logged out successfully",
      UserProfileUpdatedSuccessfully: "User profile updated successfully",
      UserNameSentSuccessfully: "Your username has been sent to the email address in our system",
      PasswordResetSuccessfully: "Password Reset Successfully",
      AccountVerificationUpdatedSuccessfully: "Provider's status has been updated successfully",
      UserPasswordUpdatedSuccessfully: "User password updated successfully",
      UserStatusUpdatedSuccessfully: "User status updated successfully",

      ProviderUpdateSuccessful: "Provider's updated successfully",
      ProviderStatusUpdateSuccessful: "Provider status updated successfully",
      ProviderBillingUpdateSuccessful: "Provider's billing status updated successfully",
      AccountVerificationUpdatedSuccessfully: "Provider's status has been updated successfully",
      RoleCreatedSuccessfully : "Role created successfully",
      RoleUpdatedSuccessfully : "Role updated successfully",
      RoleDeletedSuccessfully : "Role deleted successfully",
      OrganizationCreatedSuccessfully : "Organization created successfully",
      OrganizationUpdatedSuccessfully : "Organization updated successfully",
      LocationCreatedSuccessfully : "Location created successfully",
      LocationUpdatedSuccessfully : "Location updated successfully",
      SpecialityCreatedSuccessfully : "Specialty created successfully",
      SpecialityUpdatedSuccessfully : "Specialty updated successfully",
      AccessControlCreatedSuccessfully : "Access control created successfully",
      AccessControlUpdatedSuccessfully : "Access control updated successfully",
      NavigationControlCreatedSuccessfully : "Navigation control created successfully",
      NavigationControlUpdatedSuccessfully : "Navigation control updated successfully",
      RegisterInviteCreatedSuccessfully : "Invite Send Successfully",
      ResendInviteCreatedSuccessfully : "Invite Resend Successfully",
      InviteStatusUpdatedSuccessfully : "Invite status updated successfully",
      ConfigUpdatedSuccessfully : "Configurations updated successfully",
      ConfigCreatedSuccessfully : "Configuration created successfully"
  },
  DynamicMessage: {
      EmailAlreadyExist: "User with this email #email# already exists",
      EmailNotInSystem: "User with #email# does not exist in the system.",
      EmailNotMatchedWithInvite: "User with this email #email# not matched with invite",
      EmailNotMatchedWithInviteRole: "User with this email #email# not matched with invite role",
      EmailAlreadyRegistered: "User with this email #email# already registered",
      EmailAlreadyCancelled: "User with this email #email# already invite cancelled",
      ProfileImageNotFound: "Profile Image with id #id# not found",
      UserNotFound: "User with id #id# not found",
      UserNotInSystem: "User with #id# does not exist in the system",

      LocationAlreadyExist: "Location with this name #name# already exists",
      OrganizationAlreadyExist: "Organization with this name #name# already exists",
      ProviderIdNotFound: "Provider with id #id# not found",
      UserEmailAlreadyExist: "User with this email #email# already exists",
      InviteEmailAlreadyExist: "Invite with this email #email# already exists",
      SpecialityAlreadyExist: "Speciality with this name #name# already exists"
  }
};